### ISSUE TITLE
Update TIKI SDK JS to Use Base Font Size Instead of REM

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-js#74]
TIKI SDK JS relies on using the rem unit for sizing, which can lead to unexpected behavior when the HTML root element has a custom font size instead of the default browser size of 16px. This is particularly noticeable in pages like the Shopify standard theme, where the base font size is set to 10px, causing font sizes in the TIKI UI to appear smaller than intended.

![Captura de Tela 2023-05-31 às 17 03 35](https://github.com/tiki/tiki-sdk-js/assets/8357343/fe1a12d9-1aa8-4085-8ec1-d546a0e6f441)

To address this issue, we need to update the TIKI SDK JS UIs to use a base font size of 16px instead of relying on the rem unit for sizing. This will ensure consistent and expected font sizes across different environments and themes.

## Tasks:
- [x] Update the TIKI SDK JS UI CSS codebase to set the base font size to 16px.
- [x] Replace all instances of using rem for font sizing with the updated base font size.
- [x] Test the updated TIKI SDK JS in different environments and themes to verify the font sizes are consistent and correct.

**Comment by ricardobrg** [comment]
These are the rules that we are using in the Shopify integration. It fixes the UI for the integration.
```
<style>
    :root {
        --tiki-font-size-xs: calc(16px * 0.75);
        --tiki-font-size-sm: calc(16px * 0.875);
        --tiki-font-size: calc(16px * 1);
        --tiki-font-size-lg: calc(16px * 1.125);
        --tiki-font-size-xl: calc(16px * 1.25);
        
        --tiki-line-height-xs: calc(16px * 1);
        --tiki-line-height-sm: calc(16px * 1.25);
        --tiki-line-height: calc(16px * 1.5);
        --tiki-line-height-lg: calc(16px * 1.75);
        --tiki-line-height-xl: calc(16px * 1.75);

        --page-width: calc(16px * 160);
        --product-card-corner-radius: calc(16px * 0.4);
        --product-card-shadow-blur-radius: calc(16px * 1.0);
        --collection-card-corner-radius: calc(16px * 0.4);
        --collection-card-shadow-vertical-offset: calc(16px * 0.4);
        --collection-card-shadow-blur-radius: calc(16px * 0.5);
        --blog-card-shadow-vertical-offset: calc(16px * 0.4);
        --blog-card-shadow-blur-radius: calc(16px * 0.5);
        --badge-corner-radius: calc(16px * 4.0);
    }
    .tiki-back-btn{
        height:16px!important;
    }
</style>
```
