### ISSUE TITLE
Expose UI Elements for External Usage

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-js#75]
[The export line in the ui.ts file is commented out](https://github.com/tiki/tiki-sdk-js/blob/8b9adaca1b1f07f374b28ff39e93d2b3771af6bf/src/ui/ui.ts#L16), preventing the UI elements from being used externally. We need to investigate whether uncommenting this line resolves the issue and makes the UI elements ready to use, or if an alternative approach is needed.

## Tasks:

- [x] Uncomment the export line and verify if it enables the UI elements to be used externally.
- [x] Test the usage of the UI elements in different scenarios to ensure they function as expected.
- [x] If uncommenting the export line does not resolve the issue or presents unintended consequences, explore alternative approaches for exposing the UI elements. Create necessary issues for implementing it.

**Comment by ricardobrg** [comment]
In order to use the UIs and create custom flows, like the one we are using in Shopify integration, I added the elements and the screens to the UI export. 

Now elements and screens can be accessed by:

TikiSdk.UI.Ending
TikiSdk.UI.LearnMore
TikiSdk.UI.Prompt
TikiSdk.UI.Settings
TikiSdk.UI.Terms
TikiSdk.UI.BackBtn
TikiSdk.UI.LearnMoreBtn
TikiSdk.UI.OfferCard
TikiSdk.UI.Overlay
TikiSdk.UI.TextBtn
TikiSdk.UI.TradeYourDataBadge
TikiSdk.UI.UsedFor
TikiSdk.UI.YourChoiceBadge

**Comment by ricardobrg** [comment]
![Image](https://github.com/tiki/tiki-sdk-js/assets/8357343/b96e39ba-194d-4be2-aeb8-1ed94484665c)
